vich_uploader:
    db_driver: orm
    mappings:
        t_content_images:
            uri_prefix: /images/uploads
            upload_destination: '%kernel.project_dir%/public/images/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true

        # t_content_video:
        #     uri_prefix: /uploads/videos
        #     upload_destination: '%kernel.project_dir%/public/uploads/videos'
        #     namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        #     delete_on_remove: true
        #     delete_on_update: true